### ISSUE TITLE
couldn't find file 'formtastic'

### ISSUE THREAD

**Issue by emaiax** [damjack/spree_banner#1]
After installing spree_banner on my Rails 3.2.3 and Spree (head) app, I try to access my admin module and I got:

couldn't find file 'formtastic'
  (in /Users/eduardo/.rvm/gems/ruby-1.9.3-p125-perf@ifood/gems/spree_banner-1.0.4/app/assets/stylesheets/admin/spree_banner.css:3)

The head of spree_banner.css is written down below but there's no such file (formtastic.css)

/*
 *= require admin/spree_core
 *= require formtastic
*/

Greetings.

**Comment by damdiginess** [comment]
Fixed bug in lib/spree_banner.rb for require 'formtastic'.
Update gem at 1.0.7
